apiVersion: v1
kind: Service
metadata:
  name: {{ include "auto.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
  selector:
    {{- include "auto.selectorLabels" . | nindent 4 }}
