apiVersion: v2
name: auto
description: Auto Kilometerstand Tracker - PWA deployed on Kubernetes with GitOps (ArgoCD)

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. The actual version is set during CI/CD from Git tags.
# This fixed version is overridden by helm package --version in the release workflow.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0-dev

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

# Repository and maintainer information
home: https://github.com/Hawk-Softworks/auto
sources:
  - https://github.com/Hawk-Softworks/auto
maintainers:
  - name: Hawk-Softworks
